routes/web.php
<?php

Route::get('/', function () {
    return view('welcome');
});

Route::get('/discuss', function () {
    return view('discuss');
});

Auth::routes();

Route::get('/forum', [
    'uses' => 'ForumsController@index',
    'as' => 'forum'
]);
Route::get('/discussion/{slug}', [
    'uses' => 'DiscussionsController@show',
    'as' => 'discussion'
]);
Route::get('/channel/{slug}',[
    'uses' => 'ForumsController@channel',
    'as' => 'channel'
]);

Route::group(['middleware' => 'auth'], function () {

    Route::resource('channels', 'ChannelsController');

    Route::get('/discussion/create/new', [
        'uses' => 'DiscussionsController@create',
        'as' => 'discussions.create'
    ]);
    Route::post('/discussions/store', [
        'uses' => 'DiscussionsController@store',
        'as' => 'discussions.store'
    ]);

    Route::post('/discussions/reply/{id}', [
        'uses' => 'DiscussionsController@reply',
        'as' => 'discussion.reply'
    ]);
    Route::get('/reply/like/{id}',[
        'uses' => 'RepliesController@like',
        'as' => 'reply.like'
    ]);
    Route::get('/reply/unlike/{id}',[
        'uses' => 'RepliesController@unlike',
        'as' => 'reply.unlike'
    ]);
    Route::get('/discussion/watch/{id}',[
        'uses' => 'WatchersController@watch',
        'as' => 'discussion.watch'
    ]);
    Route::get('/discussion/unwatch/{id}',[
        'uses' => 'WatchersController@unwatch',
        'as' => 'discussion.unwatch'
    ]);
    Route::get('/discussion/best/reply/{id}',[
        'uses' => 'RepliesController@best_answer',
        'as' => 'discussion.best.answer'
    ]);
    Route::get('/discussion/edit/{slug}',[
        'uses' => 'DiscussionsController@edit',
        'as' => 'discussion.edit'
    ]);
    Route::post('/discussion/update/{id}',[
        'uses' => 'DiscussionsController@update',
        'as' => 'discussion.update'
    ]);
    Route::get('/reply/edit/{id}',[
        'uses' => 'RepliesController@edit',
        'as' => 'reply.edit'
    ]);
    Route::post('/reply/update/{id}',[
        'uses' => 'RepliesController@update',
        'as' => 'reply.update'
    ]);
});

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css"
          integrity="sha512-vKMx8UnXk60zUwyUnUPM3HbQo8QfmNx7+ltw8Pm5zLusl1XIfwcxo8DbWCqMGKaWeNxWA8yrx5v3SaVpMvR3CA=="
          crossorigin="anonymous"/>
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.1/styles/default.min.css">
</head>
<body>
<div id="app">
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">

                <!-- Collapsed Hamburger -->
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#app-navbar-collapse">
                    <span class="sr-only">Toggle Navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <!-- Branding Image -->
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
            </div>

            <div class="collapse navbar-collapse" id="app-navbar-collapse">
                <!-- Left Side Of Navbar -->
                <ul class="nav navbar-nav">
                    &nbsp;
                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="nav navbar-nav navbar-right">
                    <!-- Authentication Links -->
                    @if (Auth::guest())
                        <li><a href="{{ route('login') }}">Login</a></li>
                        <li><a href="{{ route('register') }}">Register</a></li>
                    @else
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                               aria-expanded="false">
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>

                            <ul class="dropdown-menu" role="menu">
                                <li>
                                    <a href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        Logout
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST"
                                          style="display: none;">
                                        {{ csrf_field() }}
                                    </form>
                                </li>
                            </ul>
                        </li>
                    @endif
                </ul>
            </div>
        </div>
    </nav>

    @if($errors->count()>0)
        <ul class="list-group-item">
            @foreach($errors->all() as $error)
                <li class="list-group-item text-danger">
                    {{$error}}
                </li>
            @endforeach
        </ul>
        <br>
        <br>
    @endif


    <div class="container">
        <div class="col-md-4">
            <a href="{{route('discussions.create')}}" class="form-control btn btn-primary">Create a new discussion</a>
            <br>
            <br>
            <div class="panel panel-default">
                <div class="panel-body">
                    <ul class="list-group">
                        <li class="list-group-item">
                            <a href="{{route('forum')}}" style="text-decoration: none">Home</a>
                        </li>
                        <li class="list-group-item">
                            <a href="/forum?filter=me" style="text-decoration: none">My Discussions</a>
                        </li>
                        <li class="list-group-item">
                            <a href="/forum?filter=solved" style="text-decoration: none">Answered Discussions</a>
                        </li>
                        <li class="list-group-item">
                            <a href="/forum?filter=unsolved" style="text-decoration: none">Unanswered Discussions</a>
                        </li>
                    </ul>
                </div>
               @if(Auth::check())
                    @if(Auth::user()->admin)
                        <div class="panel-body">
                            <ul class="list-group">
                                <li class="list-group-item">
                                    <a href="{{route('channels.index')}}" style="text-decoration: none">All Channels</a>
                                </li>
                            </ul>
                        </div>
                    @endif
                @endif
            </div>
            <div class="panel panel-default">
                <div class="panel-heading">
                    Channels
                </div>
                <div class="panel-body">
                    <ul class="list-group">
                        @foreach($channels as $channel)
                            <li class="list-group-item">
                                <a href="{{route('channel',['slug'=>$channel->slug])}}"
                                   style="text-decoration: none">{{$channel->title}}</a>
                            </li>
                        @endforeach
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-md-8">
            @yield('content')
        </div>
    </div>
</div>


<!-- Scripts -->
<script src="{{ asset('js/app.js') }}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"
        integrity="sha512-VEd+nq25CkR676O+pLBnDW09R7VQX9Mdiij052gVCp5yVH3jGtH70Ho/UUv4mJDsEdTvqRCFZg0NKGiojGnUCw=="
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.1/highlight.min.js"></script>
<script>hljs.initHighlightingOnLoad();</script>
<script>
    @if(Session::has('success'))
    toastr.success('{{Session::get('success')}}')
    @endif
</script>
</body>
</html>